# Generated by Django 5.1.2 on 2024-11-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='bloodPressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='bmi',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='diabetesPedigreeFunction',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='glucose',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='insulin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='outcome',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='pregnancies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='skinThickness',
            field=models.IntegerField(),
        ),
    ]
